export const Cities = [
  { name: "Jerusalem" },
  { name: "Haifa" },
  { name: "Jaffa" },
  { name: "Hebron" },
  { name: "Bethlehem" },
  { name: "Jericho" },
  { name: "Nablus" },
  { name: "Gaza" },
  { name: "Safed" },
  { name: "Beersheba" },
  { name: "Tiberias" },
  { name: "Akka" },
  { name: "Nazareth" },
  { name: "Ramallah" },
  { name: "Beirah" },
];
