const tests = [
  {
    title: "Final Driving Test",
    date: "October 5, 2024",
    duration: "60 mins",
    tester: "Ibrahim Qadi",
    score: 28,
  },
  {
    title: "Intermediate Test",
    date: "September 15, 2024",
    duration: "45 mins",
    tester: "Ibrahim Qadi",
    score: 26,
  },
  {
    title: "Basic Test",
    date: "August 25, 2024",
    duration: "45 mins",
    tester: "Ibrahim Qadi",
    score: 22,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
  {
    title: "Parking Test",
    date: "August 1, 2024",
    duration: "30 mins",
    tester: "Ibrahim Qadi",
    score: 18,
  },
];
export { tests };
